<?php /** @var \Rprotsenko\DevTestImport\Controller\ImportAction $this */ ?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Import Sitemap</title>

    <link href="/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="/css/style.css" rel="stylesheet">
</head>

<body>

<?php \Snowdog\DevTest\Component\Menu::getInstance()->render() ?>

<div class="container">

    <?php if (isset($_SESSION['flash'])): ?>
        <p class="bg-info"><?= $_SESSION['flash'] ?></p>
        <?php unset($_SESSION['flash']) ?>
    <?php endif ?>

    <div>
        <h1>Import Sitemap</h1>
        <?php if ($this->user): ?>

            <div class="padded">
                <form class="form-inline" enctype="multipart/form-data" method="post" action="/import">
                    <div class="form-group">
                        <label for="exampleSelectName">Website</label>
                        <select name="website" id="exampleSelectName" class="form-control">
                            <?php foreach ($this->getWebsites() as $website): /** @var \Snowdog\DevTest\Model\Website $website */ ?>
                                <option value="<?= $website->getWebsiteId() ?>"><?= $website->getName() . ' - [' .  $website->getHostname() . ']'?></option>
                            <?php endforeach ?>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="fileToUpload">Choose sitemap file</label>
                        <input type="file" name="fileToUpload" id="fileToUpload" class="form-control">
                    </div>
                    <button type="submit" class="btn btn-primary">Import</button>
                </form>
            </div>

        <?php endif ?>
    </div>

</div><!-- /.container -->


</body>
</html>
